#!/bin/bash

case $1 in 
	prdv)

        mkdir bin
	mkdir licenses
	mkdir makfiles
	mkdir sources
	touch main.sh
	touch install.sh 
	
	exit 0
 	;;
        help)
	-NAME:.initdev/  le but de cette application est d.implémenter un outil  					d.initialisation de projets.
    
        -SYNTAX:
	-syntax1 :/initdev {nom-project/type-de-langage}  #indiquer le nom et le langage
            
        -syntax2 :/initdev {nom-project/type-de-licence} #indiquer le nom et le type de la licence
                    
        -syntax3 :/initdev {nom-project/type-de-langage/git} #indiquer et le nom et le langage et 				initialiser un depot git
                    
        -syntax4:/initdev {nom-project/type-de-langage/type-de-licence/git}
                    
         ARGUMENTS: -c: programme en langage c
        
                    -cpp: programme en langage c++
                   
                    -py: programme en langage python
                    
                    -latex: redaction en latex
                    
                    -BEAMER: presentation en BEAMER
                    
                    -GPL:GENERAL PUBLIC LICENCE
                    
                    -MIT:MIT LICENCE 
		    
            AUTHOR: SAIDI Fouad  email: saidifouad23@gmail.com
 		;;

	*)
	     
	
   
        echo "Expected arguments, please check the help : projet help"
        exit 1
	;;
esac

